pipeline {
    agent any
    
    tools {
        nodejs "Node18" // 여기서 "Node18"은 위에서 설정한 Node.js의 이름입니다.
    }
    
    stages {
        

        stage('React build') {
            steps {
                dir('frontend') {
                    echo 'React build'
                    sh 'npm install' 
                    sh 'CI=false npm run build'
                }
            }
        }

        stage('Dockerimage build') {
            steps {
                dir('frontend') {
                    sh '''
                    echo 'Dockerimage build for React'
                    docker build -t docker-react:0.0.1 .
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                
                echo 'Deploy React' // 배포
                sh docker run -d -p 3000:3000 --name react docker-react:0.0.1
                
            }
        }
    }
}
