pipeline {
    agent any

    stages {
        stage('Springboot build') {
            steps {
                dir('BACKEND'){
                    sh '''
                    echo 'React build'
                    chmod +x gradlew 
                    ./gradlew clean build //스프링 부트 빌드, .jar파일 생성
                    '''
                }
            }
        }
        stage('Dockerimage build') {
            steps {
                dir('BACKEND'){
                    sh '''
                    echo 'Dockerimage build'
                    docker build -t docker-springboot:0.0.1 .//도커 이미지파일 빌드
                    '''
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('BACKEND'){
                    sh '''
                    echo 'Deploy' //배포

										// 터미널에서 최초1번 실행해 줘야 하는 부분
												// docker run -d -p 8080:8080 --name springboot docker-springboot:0.0.1
												// 스프링 구동

                    docker stop  springboot 
                    docker start springboot
                    '''
                }
            }
        }
    }
}