pipeline {
    agent any
    stages {
        stage('Springboot build') {
            steps {
                sh '''
                echo 'springboot build'
                chmod +x gradlew
                ./gradlew clean build
                '''
            }
        }
        stage('Dockerimage build') {
            steps {
                sh '''
                echo 'Dockerimage build'
                docker build -t docker-springboot:0.0.1
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                echo 'Deploy'
                docker run -d -p 8080:8080 docker-springboot
                '''
            }
        }


    }
}